name: Ci pipeline to execute tests on DEV environment, generate test execution report, and send email notification.

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - run: python3 install_poetry.py
      - run: poetry --version
      - run: poetry install --no-root
      - run: source `poetry env info --path`/bin/activate

      - run: poetry run python generate_config.py

      - name: Working with ENV variables
        run: |
          echo "The API key is:${{vars.DEV_FACILITY_ADMIN_EMAIL}}"
          echo "The API key is:${{secrets.DEV_FACILITY_ADMIN_EMAIL}} ${{secrets.DEV_ENV}}"
          echo "The API key is:${{env.DEV_FACILITY_ADMIN_EMAIL}}"
          echo "The API key is:${{main.DEV_FACILITY_ADMIN_EMAIL}}"
          echo "GitHub actor:${{GITHUB_ACTOR}}"

#      - name: Executing tests
#        run: |
#          poetry run python -m pytest -s --env=dev
#        continue-on-error: true
