name: Ci pipeline to execute tests on DEV environment, generate test execution report, and send email notification.

on:
  schedule:
  - cron: "0 9 * * *"
  
jobs:
  test:
    name: Execute tests on DEV environment
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
        
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config settings.virtualenvs.in-project false
          poetry config settings.virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
        
      - name: Test with pytest
        run: "Hello Mars! ..."
    
