name: Ci pipeline to execute tests on DEV environment, generate test execution report, and send email notification.

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry, install requirements, and activate venv.
        run: |
          echo "The job was triggered by: $GITHUB_ACTOR"
          python3 install_poetry.py
          poetry --version
          poetry install --no-root
          source `poetry env info --path`/bin/activate

      - name: Create .config.yaml file.
        env:
          DEV_SUPERUSER_EMAIL: ${{ vars.DEV_SUPERUSER_EMAIL }}
          DEV_FACILITY_ADMIN_EMAIL: ${{ vars.DEV_FACILITY_ADMIN_EMAIL }}
          DEV_FACILITY_DRIVER_EMAIL: ${{ vars.DEV_FACILITY_DRIVER_EMAIL }}
          DEV_FACILITY_USER_EMAIL: ${{ vars.DEV_FACILITY_USER_EMAIL }}
          PASSWORD: ${{ vars.PASSWORD }}
        run: |
          poetry run python generate_config.py

#      - name: Executing tests
#        run: |
#          poetry run python -m pytest -s --env=dev
#        continue-on-error: true
